import PDFDocument from "pdfkit";

export interface VoucherData {
  voucherNumber: string;

  customerName: string;
  customerEmail: string;

  planName: string;

  amount: string;
  currency: string;

  paymentDate: Date;

  periodStart?: Date;
  periodEnd?: Date;

  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  stripePaymentIntentId?: string;
}

export const generateSubscriptionVoucher = async (
  data: VoucherData,
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
      });

      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => {
        chunks.push(chunk);
      });

      doc.on("end", () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });

      doc.on("error", (error) => {
        reject(error);
      });

      // =========================
      // Header
      // =========================

      doc.fontSize(24).font("Helvetica-Bold").text("HR Management", {
        align: "center",
      });

      doc.moveDown(0.5);

      doc.fontSize(18).font("Helvetica-Bold").text("PAYMENT VOUCHER", {
        align: "center",
      });

      doc.moveDown(1);

      // =========================
      // Voucher Info
      // =========================

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Voucher Number: ${data.voucherNumber}`);

      doc.text(
        `Payment Date: ${data.paymentDate.toLocaleString("en-US", {
          dateStyle: "medium",
          timeStyle: "short",
        })}`,
      );

      doc.moveDown(1);

      // =========================
      // Customer
      // =========================

      doc.fontSize(13).font("Helvetica-Bold").text("Customer Information");

      doc.moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Name: ${data.customerName}`)
        .text(`Email: ${data.customerEmail}`);

      doc.moveDown(1);

      // =========================
      // Payment Details
      // =========================

      doc.fontSize(13).font("Helvetica-Bold").text("Payment Details");

      doc.moveDown(0.5);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Plan: ${data.planName}`)
        .text(`Amount: ${data.amount} ${data.currency.toUpperCase()}`)
        .text("Payment Status: PAID");

      if (data.periodStart) {
        doc.text(
          `Billing Period Start: ${data.periodStart.toLocaleDateString(
            "en-US",
          )}`,
        );
      }

      if (data.periodEnd) {
        doc.text(
          `Billing Period End: ${data.periodEnd.toLocaleDateString("en-US")}`,
        );
      }

      doc.moveDown(1);

      // =========================
      // Stripe Information
      // =========================

      doc.fontSize(13).font("Helvetica-Bold").text("Transaction Information");

      doc.moveDown(0.5);

      doc.fontSize(9).font("Helvetica");

      if (data.stripeCustomerId) {
        doc.text(`Stripe Customer ID: ${data.stripeCustomerId}`);
      }

      if (data.stripeSubscriptionId) {
        doc.text(`Stripe Subscription ID: ${data.stripeSubscriptionId}`);
      }

      if (data.stripePaymentIntentId) {
        doc.text(`Stripe Payment Intent ID: ${data.stripePaymentIntentId}`);
      }

      doc.moveDown(2);

      // =========================
      // Footer Message
      // =========================

      doc.fontSize(11).font("Helvetica-Bold").text("Payment Successful", {
        align: "center",
      });

      doc.moveDown(0.5);

      doc
        .fontSize(9)
        .font("Helvetica")
        .text("Thank you for subscribing to HR Management.", {
          align: "center",
        });

      doc.moveDown(2);

      doc
        .fontSize(8)
        .fillColor("gray")
        .text("This voucher was automatically generated by HR Management.", {
          align: "center",
        });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
